[2025-04-06T02:29:05.472+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T02:29:05.680+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_data.fetching_and_modelling manual__2025-04-05T20:39:39.044473+00:00 [queued]>
[2025-04-06T02:29:05.793+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_data.fetching_and_modelling manual__2025-04-05T20:39:39.044473+00:00 [queued]>
[2025-04-06T02:29:05.797+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-06T02:29:06.028+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): fetching_and_modelling> on 2025-04-05 20:39:39.044473+00:00
[2025-04-06T02:29:06.040+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-04-06T02:29:06.050+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_and_store_data', 'fetching_and_modelling', 'manual__2025-04-05T20:39:39.044473+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/reverse_etl_dag.py', '--cfg-path', '/tmp/tmpho11xl42']
[2025-04-06T02:29:06.060+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask fetching_and_modelling
[2025-04-06T02:29:06.357+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_data.fetching_and_modelling manual__2025-04-05T20:39:39.044473+00:00 [running]> on host 830eaf47e7f8
[2025-04-06T02:29:06.875+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_and_store_data' AIRFLOW_CTX_TASK_ID='fetching_and_modelling' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T20:39:39.044473+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-05T20:39:39.044473+00:00'
[2025-04-06T02:29:06.878+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T02:29:06.933+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-06T02:29:06.937+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', ' cd /usr/local/airflow/workfile && python datamodelling.py']
[2025-04-06T02:29:06.964+0000] {subprocess.py:99} INFO - Output:
[2025-04-06T02:29:25.980+0000] {subprocess.py:106} INFO - [2025-04-06T02:29:25.977+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-04-06T02:32:39.298+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-06T02:32:39.304+0000] {subprocess.py:106} INFO -   File "/usr/local/airflow/workfile/datamodelling.py", line 50, in <module>
[2025-04-06T02:32:39.324+0000] {subprocess.py:106} INFO -     modelling_data(data)
[2025-04-06T02:32:39.326+0000] {subprocess.py:106} INFO -   File "/usr/local/airflow/workfile/datamodelling.py", line 40, in modelling_data
[2025-04-06T02:32:39.340+0000] {subprocess.py:106} INFO -     cursor.execute("""
[2025-04-06T02:32:39.346+0000] {subprocess.py:106} INFO - psycopg2.OperationalError: SSL SYSCALL error: EOF detected
[2025-04-06T02:32:39.349+0000] {subprocess.py:106} INFO - 
[2025-04-06T02:32:40.925+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-06T02:32:40.963+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-06T02:32:40.980+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fetch_and_store_data, task_id=fetching_and_modelling, run_id=manual__2025-04-05T20:39:39.044473+00:00, execution_date=20250405T203939, start_date=20250406T022905, end_date=20250406T023240
[2025-04-06T02:32:41.141+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T02:32:41.142+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task fetching_and_modelling (Bash command failed. The command returned a non-zero exit code 1.; 87)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-06T02:32:41.193+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T02:32:41.351+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-06T02:32:42.402+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T02:32:42.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
